### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by crdil** [smartsheet-platform/backup-java#14]
I few days ago I started getting this error when I run the backup tool

```
"C:\Program Files\Java\jre1.8.0_91\bin\java.exe" -jar "C:\smartsheet\smartsheet-org-backup-1.6.1.jar"
Using properties file: c:\smartsheet\smartsheet-backup.properties
***ERROR*** NullPointerException - null
java.lang.NullPointerException
        at com.smartsheet.tools.SmartsheetBackupService.backupOrgTo(SmartsheetBackupService.java:115)
        at com.smartsheet.tools.SmartsheetBackupTool.main(SmartsheetBackupTool.java:107)
```

How can I fix this?

**Comment by seweil** [comment]
We've identified the underlying problem. I'll update here as soon as we have a resolution.

**Comment by seweil** [comment]
We released a product update on 21-December that should correct this problem. Please let us know if you encounter any more issues.

**Comment by lijuram1** [comment]
I am also facing with the same issue. From where can i get the new update.

**Comment by BraamM** [comment]
Hi, I'm also getting this error now. Using version smartsheet-org-backup-1.6.1.
Any idea how to resolve this?
Thanks.

**Comment by lijuram1** [comment]
@BraamM   U don't have SysAdmin  privileges for the smartsheet. Thats why it throws Null pointer exception. Hope this helps :)

**Comment by BraamM** [comment]
Hi

Great, thank you. I was under the impression it would be able to backup my
own sheets using the API token I generated.

I'll have the Administrator generate the token.

Thanks,
Braam.

**Comment by lijuram1** [comment]
@BraamM  If you or the team that you work are the only ones using Smartsheet ,then administrator will most probably give u the token. But if multiple teams are involved then some Data privacy concerns can come across. Just a thumps up . Coz i am hearing these from my IT administrator :smiley:

**Comment by BraamM** [comment]
Perfect, thank you!
