### ISSUE TITLE
Null error running v.1.6.1

### ISSUE THREAD

**Issue by hchav01** [smartsheet-platform/backup-java#15]
We are receiving an error when running 1.6.1:

c:\Service\smartsheet-org-backup-1.6.1>java -jar smartsheet-org-backup-1.6.1.jar
Using properties file: c:\Service\smartsheet-org-backup-1.6.1\smartsheet-backup.properties
***ERROR*** NullPointerException - null
java.lang.NullPointerException
        at com.smartsheet.tools.SmartsheetBackupService.backupOrgTo(SmartsheetBackupService.java:115)
        at com.smartsheet.tools.SmartsheetBackupTool.main(SmartsheetBackupTool.java:107)

It successfully creates the folder structure for the backup and entered in the properties files but that is all that it does.

**Comment by lijuram1** [comment]
is there any update on this issue? I am facing the same problem during back up.

**Comment by BraamM** [comment]
Getting the same issue. Also create folders, but no data. Same Error message.
(Running Windows 10)

**Comment by ellelong** [comment]
any news on this, i am also getting this error?
