### ISSUE TITLE
SSLHandshakeException - Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by sudhird81** [smartsheet-platform/backup-java#23]
Hello 

I am new to this, I followed all steps but when I ran application I got below error 

`***ERROR*** SSLHandshakeException - Received fatal alert: handshake_failure
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1979)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1086)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
	at org.apache.http.conn.ssl.SSLSocketFactory.createLayeredSocket(SSLSocketFactory.java:573)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:557)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:414)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.smartsheet.utils.HttpUtils.getResponse(HttpUtils.java:166)
	at com.smartsheet.utils.HttpUtils.getJsonPayload(HttpUtils.java:63)
	at com.smartsheet.restapi.service.RestfulSmartsheetService.getJsonPayload(RestfulSmartsheetService.java:85)
	at com.smartsheet.restapi.service.RestfulSmartsheetService.getUsers(RestfulSmartsheetService.java:51)
	at com.smartsheet.restapi.service.RetryingSmartsheetService.getUsers(RetryingSmartsheetService.java:56)
	at com.smartsheet.restapi.service.ErrorContextualizingSmartsheetService.getUsers(ErrorContextualizingSmartsheetService.java:50)
	at com.smartsheet.tools.SmartsheetBackupService.backupOrgTo(SmartsheetBackupService.java:94)
	at com.smartsheet.tools.SmartsheetBackupTool.main(SmartsheetBackupTool.java:107)`

Any help will be appreciated to this issue. 

Thanks

**Comment by XpertDesperado** [comment]
I'm also seeing this issue.

**Comment by apratimg** [comment]
I was able to fix it by just upgrading to the latest JRE. I never thought it will be a fix, did it as hunch :-) 

I used Java SE Runtime Environment 8u251. Hope you find this useful..
