### ISSUE TITLE
Unhandled invalid file names

### ISSUE THREAD

**Issue by KennyDeardorff** [smartsheet-platform/backup-java#28]
### Description
Somehow, a folder was created in Smartsheet with a carriage return in the folder name. When the backup script tried to create this folder, it threw a `CreateFileSystemItemException` and stopped scanning for files/folders and moved on to the next user.

### Desired behavior
I would like the script to be able to handle this kind of error so that as many sheets are backed up as possible. I think the best solution would be to remove the invalid characters from the file/folder name and continue recursing. Second best option might be to skip that file/folder, but continue with the next sibling/parent folder.

### Details
Script version: 1.6.2
Downloading to a Windows file system
`continueOnError=true`

### Call Stack
Note the line break in `Folder With<newline>Newline In Name`
```
com.smartsheet.exceptions.CreateFileSystemItemException: C:\Temp\smartsheet-backup\smartsheet-backup\2020-06-11_15_12_57\[user@user.com]\Workspaces\Folder 1\Folder 2\Folder 3\Folder With 
Newline In Name could not be created
	at com.smartsheet.tools.SmartsheetBackupService.createNewFolderQuietly(SmartsheetBackupService.java:322)
	at com.smartsheet.tools.SmartsheetBackupService.createNewFolder(SmartsheetBackupService.java:307)
	at com.smartsheet.tools.SmartsheetBackupService.createFoldersRecursively(SmartsheetBackupService.java:337)
	at com.smartsheet.tools.SmartsheetBackupService.createFoldersRecursively(SmartsheetBackupService.java:346)
	at com.smartsheet.tools.SmartsheetBackupService.createFoldersRecursively(SmartsheetBackupService.java:346)
	at com.smartsheet.tools.SmartsheetBackupService.createFoldersRecursively(SmartsheetBackupService.java:346)
	at com.smartsheet.tools.SmartsheetBackupService.backupTo(SmartsheetBackupService.java:197)
	at com.smartsheet.tools.SmartsheetBackupService.assumeUserAndBackup(SmartsheetBackupService.java:160)
	at com.smartsheet.tools.SmartsheetBackupService.backupOrgTo(SmartsheetBackupService.java:122)
	at com.smartsheet.tools.SmartsheetBackupTool.main(SmartsheetBackupTool.java:107)
```

**Comment by KennyDeardorff** [comment]
It looks like the code is already trying to scrub the file/folder names, but it just wasn't expecting a carriage return/line feed:

https://github.com/smartsheet-platform/backup-java/blob/e25f95b46984ead064baf31e82bc70616093e801/src/main/java/com/smartsheet/tools/SheetSaver.java#L211-L214
