### ISSUE TITLE
403 Connection is refused at https://api.smartsheet.com

### ISSUE THREAD

**Issue by mtbikes** [smartsheet-platform/backup-java#7]
I get a connection refused error. I am a developer and our site admin gave me the access token. ANy idea why I get a 403?

**Comment by alexvor** [comment]
@mtbikes Thanks for reaching out.  Can you please ping us at api@smartsheet.com with additional details, including:
- have you updated your smartsheet-backup.properties file with the token, etc.
- are you able to connect to the Smartsheet API directly, using cURL or a browser extension
- can you please send us your log file. log messages are printed to stdout, so you may need to redirect them to a file

Please send this to api@smartsheet.com.  Thanks in advance!

**Comment by 786abdul** [comment]
Hi alexvor,
i am also facing the same issue
please find the error below:
[main] WARN com.smartsheet.api.internal.http.DefaultHttpClient - {request:{command:'GET https://api.smartsheet.com/2.0/sheets/2639777414571908',headers:{'Accept':'application/vnd.ms-excel','Authorization':'Bearer ****s2x3','Content-Type':'application/json','User-Agent':'Smartsheet Java SDK/2.83.0/smartsheet-sdk-java-2.83.0.jar!com.smartsheet.api.SmartsheetBuilder/Windows 10 Java HotSpot(TM) 64-Bit Server VM Oracle Corporation 1.8.0_211',},},response:{status:'null',}}
Exception in thread "main" com.smartsheet.api.internal.http.HttpClientException: Error occurred.
	at com.smartsheet.api.internal.http.DefaultHttpClient.request(DefaultHttpClient.java:356)
	at com.smartsheet.api.internal.SheetResourcesImpl.getSheetAsFile(SheetResourcesImpl.java:1202)
	at com.smartsheet.api.internal.SheetResourcesImpl.getSheetAsExcel(SheetResourcesImpl.java:346)
	at com.smartsheet.fetchsheet.Fetch.main(Fetch.java:53)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to api.smartsheet.com:443 [api.smartsheet.com/204.2.135.68] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.smartsheet.api.internal.http.DefaultHttpClient.request(DefaultHttpClient.java:240)
	... 3 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)

**please suggest how to reolve. if run the code working fine in my pc but in company pc it is throwing this error.**


Thanks & Regards
abdul

**Comment by alexvor** [comment]
I am no longer at Smartsheet.  Including the Smartsheet developer relations
team devrel@smartsheet.com.  Tx
